In [3]:
import numpy as np

In [2]:
#Creating an array of 10 zeros

In [3]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#creating an array of 10 ones

In [5]:
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#creating an array of 10 fives

In [10]:
c=np.zeros(10) +5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [11]:
#creating an array of intiger from 10 to 50

In [12]:
d=np.arange(10,51)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [13]:
#creating an array of even intiger between 10 and 50

In [17]:
e=np.arange(10,51,2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
e=np.arange(10,50)
f=np.where(e%2==0)
print(f)

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38], dtype=int64),)


In [15]:
e=np.arange(10,51,2) +1
e

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51])

In [ ]:
#creating a 3 x3 matrix with values ranging fro 0 to 8

In [21]:
g=np.arange(0,9).reshape(3,3)
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#creating a 3 x3 identity matrix

In [22]:
h=np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#Use numpy to generate random number between 0 and 1

In [103]:
np.random.normal(0,1)

-1.0271895727437461

In [39]:
i=np.random.rand()
i

0.016485762183804598

In [40]:
np.random.rand(25)

array([0.29561593, 0.98339673, 0.85845128, 0.9701469 , 0.41205237,
       0.65033377, 0.86029051, 0.63117381, 0.19344727, 0.09971932,
       0.37121528, 0.55555444, 0.43573859, 0.02857127, 0.96461213,
       0.02957502, 0.9435428 , 0.22258133, 0.56161442, 0.69088208,
       0.06961869, 0.32521661, 0.16064122, 0.91027699, 0.43049349])

In [ ]:
# creating 

In [49]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
#creating an array of 20 linearly spaced points btw 0 and 1

In [51]:
a=np.linspace(0,1,20)
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [52]:
#Numpy indexing and Selection

In [4]:
k=np.arange(1,26).reshape(5,5)
k

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
k[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [67]:
k[2:][:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [71]:
k[3][4]

20

In [83]:
k[:3][:,1]

array([ 2,  7, 12])

In [87]:
k[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#Calculating the sum of Array

In [88]:
k.sum()

325

In [ ]:
#Calculating the sum of a column

In [90]:
k.sum(axis=0) #column

array([55, 60, 65, 70, 75])

In [91]:
k.sum(axis=1) #Row

array([ 15,  40,  65,  90, 115])

In [ ]:
#Calculating the standard deviation

In [89]:
k.std()

7.211102550927978

In [7]:
import numpy as np

a = np.array([66,77,21,18,19,7,3,1])
print(a[1:5:4])


[77]


In [9]:
a = []
for i in range(1,10):
    a.append(i)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
print(a[1:7])

[2, 3, 4, 5, 6, 7]
