In [2]:


import numpy as np
#a=np.zeros((2,3),dtype=np.float64)
#print(a)

In [3]:
#a=np.array([[0,1,2],[3,4,5]], dtype=np.float64)
#print(a)

In [4]:
#b=np.arange(6,dtype=np.float64).reshape(2,3)
#print(b)

In [5]:
#one dimensional array

In [6]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b=np.array([5,7,9, 21])
b

array([ 5,  7,  9, 21])

In [8]:
# Two dimensional array
d=np.array([[5,7,9,21],[1,2,3,4]])
d

array([[ 5,  7,  9, 21],
       [ 1,  2,  3,  4]])

In [9]:
#c=np.array(2) #Zero dimensional array
#c

In [10]:
e=np.array([[5,7,9,21]])
e

array([[ 5,  7,  9, 21]])

In [11]:
print(e.ndmin)

AttributeError: 'numpy.ndarray' object has no attribute 'ndmin'

In [ ]:
f=np.array([[[5,7,9,2,1]]])
f

In [ ]:
f.ndim # checking the dimension of the array

In [ ]:
g=np.array([1,2,3,4], ndmin=4)
g.ndim

In [ ]:
g

In [ ]:
#Array indexing

In [ ]:
a=[1,2,3,4]
a[1]

In [12]:
b=([[1,2,3,4], [5,6,7,8]])
b[1]

[5, 6, 7, 8]

In [13]:
b[1][1]

6

In [14]:
k=np.array([[[4,2,1,3],[3,2,4,1]]])
k

array([[[4, 2, 1, 3],
        [3, 2, 4, 1]]])

In [15]:
k[0][1][2]

4

In [16]:
z=np.array([[[1,2,3,4],[5,6,7,8]],[[9,11,12,13], [15,21,40,49]]])
z

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 11, 12, 13],
        [15, 21, 40, 49]]])

In [17]:
z[1][0,2]

12

In [18]:
z[1][1,1]

21

In [19]:
z[1][1,3]

49

In [20]:
#s=np.array([[[[50,100,12,11]], [[22,31,40,51]]], ])

In [21]:
b=np.array([1,2,3,4], ndmin=4)#ndmin to covert to any dimension like, 1,2,3,4 while ndmin to check dimension
b

array([[[[1, 2, 3, 4]]]])

In [22]:
c=np.array([[[5,7,3,21]],[[2,1,3,8]],[[4,6,3,81]]])
c

array([[[ 5,  7,  3, 21]],

       [[ 2,  1,  3,  8]],

       [[ 4,  6,  3, 81]]])

In [23]:
c[1][0][1:-1]

array([1, 3])

In [24]:
c[2][0][1:-1]

array([6, 3])

In [25]:
c[-1][0][-3:-1]

array([6, 3])

In [26]:
#Array slicing(Python methods)


In [27]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [28]:
a[0:9:2]

array([1, 3, 5, 7, 9])

In [29]:
a[1:9:2]

array([2, 4, 6, 8])

In [30]:
s=np.array([[[5,7,3,21]],[[2,1,3,8]]])

In [31]:
s[0:2,0:2,1]

array([[7],
       [1]])

In [32]:
s[:,0,1]


array([7, 1])

In [33]:
w=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #output [2,5], [8,10]
w[0,1::3], w[1,2::2]

(array([2, 5]), array([ 8, 10]))

In [34]:
w[:][:,1::3]

array([[ 2,  5],
       [ 7, 10]])

In [35]:
y=np.array([[[[2,3,7,5]],[[8,9,11,15]]],[[[59, 30, 29, 15]],[[27,18, 19, 21]]]]) #[3,7] [9,11]
y

array([[[[ 2,  3,  7,  5]],

        [[ 8,  9, 11, 15]]],


       [[[59, 30, 29, 15]],

        [[27, 18, 19, 21]]]])

In [36]:
y[0]

array([[[ 2,  3,  7,  5]],

       [[ 8,  9, 11, 15]]])

In [37]:
y[1]

array([[[59, 30, 29, 15]],

       [[27, 18, 19, 21]]])

In [38]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a[0:2][1:4]

array([[ 6,  7,  8,  9, 10]])

In [39]:
print(a[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [40]:
(a[:,1:4])

array([[2, 3, 4],
       [7, 8, 9]])

In [41]:
#Data Type: Numpy data type

In [42]:
#i=integer, b=boolean, u=unsigned intiger, f=float, c=complex float,m=timedelta, M=datetime, O=object, S=string, U=Unicode string
#V=fixed chunk of memory for other type(void)

In [43]:
a=np.array([1,2,3,4])
print(a.dtype)

int32


In [44]:
b=np.array(["ik", "Justice", "Ife"])
print(b.dtype)

<U7


In [45]:
#Creating array with a defined data type(casting)

In [46]:
a=np.array([1,2,3,4], dtype='S') #casting from an int to string
print(a.dtype)

|S1


In [47]:
a=np.array([1,2,3,4], dtype='f') #converting to float
print(a)
print(a.dtype) # checking the data type

[1. 2. 3. 4.]
float32


In [48]:
a=np.array([1,2,3,4], dtype='i4')
print(a)
print(a.dtype)

[1 2 3 4]
int32


In [49]:
#converting an existing array data type by using astype()

In [50]:
a=np.array([1,2,3,4])
print(a)
v=a.astype('f')
print(v)

[1 2 3 4]
[1. 2. 3. 4.]


In [51]:
#Asssinment
#b=np.array([4.72, 3E2, 47e7]) #change it to integer
#c=np.array([99,2,0, 0.5]) # change it to boolen

In [52]:
# copy and veiw
a=np.array([1,2,3,4])
b=a
b[2]=7
print(a)
print(b)

[1 2 7 4]
[1 2 7 4]


In [53]:
a=np.array([1,2,3,4]) # to copy or save a file or dataset
b=a.copy()
b[2]=9
print(a)
print(b)

[1 2 3 4]
[1 2 9 4]


In [54]:
#To check if a datatype is copied or thesame

In [55]:
a=np.array([1,2,3,4])
b=a
c=a.view()
print(b.base)
print(c.base)

None
[1 2 3 4]


In [56]:
#Numpy array shape/reshape : it is the number of an element in each dimension. 

In [57]:
d=np.array([[1,2,3,4],[5,6,7,8]])
print(d.shape)
d

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
d=np.array([[1,2,3,4],[5,6,7,8]],ndmin=5)
d

array([[[[[1, 2, 3, 4],
          [5, 6, 7, 8]]]]])

In [59]:
#Data Type , dtype, astype

In [60]:
a=np.array([1.3,25, 2e4],)
b=a.astype('i')
print(b)

[    1    25 20000]


In [61]:
a=np.array([1.3,25, 2e4], dtype=('i'))
print(a)


[    1    25 20000]


In [62]:
b=np.array([99,2,0,0.5], dtype=('bool'))
print(b)

[ True  True False  True]


In [63]:
#Reshaping means changing shape of an array.
b=np.array([1,2,3,4])
c=b.reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [64]:
b=np.array([1,2,3,4,5,6,7,8])
c=b.reshape(2,2,2)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [65]:
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
c=b.reshape(2,2,-1)
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [66]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
c=a.reshape(1,2,-1)
print(c)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [67]:
a=np.array([25,11,28,75,18,23,14,21,19,20])
c=a.reshape(1,1,1,5,-1)
print(c)

[[[[[25 11]
    [28 75]
    [18 23]
    [14 21]
    [19 20]]]]]


In [68]:
a=np.array([25,11,28,75,18,23,14,21,19,20])
c=a.reshape(1,1,1,2,-1)
print(c)

[[[[[25 11 28 75 18]
    [23 14 21 19 20]]]]]


In [69]:
a=np.array([25,11,28,75,18,23,14,21,19,20,21,22,23,24])
c=a.reshape(1,1,1,1,1,1,1,1,2,-1)
print(c)

[[[[[[[[[[25 11 28 75 18 23 14]
         [21 19 20 21 22 23 24]]]]]]]]]]


In [70]:
#a=np.array([25,11,28,75,18,23,14,21,19,20,21,22,23,24])
#c=a.reshape(1,1,1,1,5,-1)
#print(c)

In [71]:
#unknow dimension

In [72]:
#Flatten Array

In [73]:
a=np.array([25,11,28,75,18,23,14,21,19,20,21,22,23,24])
c=a.reshape(1,1,1,1,1,1,1,1,2,-1)
print(c)

[[[[[[[[[[25 11 28 75 18 23 14]
         [21 19 20 21 22 23 24]]]]]]]]]]


In [74]:
c.reshape(-1)

array([25, 11, 28, 75, 18, 23, 14, 21, 19, 20, 21, 22, 23, 24])

In [75]:
#iterate a array numpy

In [76]:
a=np.array([1,2,3])
for i in a:
    print(i)

1
2
3


In [77]:
b=np.array([[1,2,3,4],[5,6,7,8]])
for i in b:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8


In [78]:
b=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for i in b:
    print(i)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [79]:
b=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for i in b:
    for c in i:
        for d in c:
            print(d)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [80]:
#iterating array using nditer()
b=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for i in np.nditer(b):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [81]:
b=np.array([1,2,3,4])
for i in np.nditer(b,flags=['buffered'],op_dtypes=['float64']):
    print(i)

1.0
2.0
3.0
4.0


In [82]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a[:,::2]):
    print(x)

1
3
5
7


In [83]:
#using ndenumerate to sort by giving the element their index
a=np.array([1,2,3,4,5,6,7])
for i,z in np.ndenumerate(a):
    print(i,z)
    

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7


In [84]:
a=np.array([[1,2,3],[4,5,6]]) #2 dimensional array
for i,z in np.ndenumerate(a):
    print(i,z)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [85]:
#Joining a numpy array(putting of 2 or more array in a single array)
a=np.array([1,2,3,4])
b=np.array([10,11,13,15])
c=np.concatenate((a,b))
print(c)


[ 1  2  3  4 10 11 13 15]


In [86]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
d=np.concatenate((a,b),axis=1)
print(d)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [87]:
#joining using stack

In [88]:
a=np.array([1,2,3,4])
b=np.array([10,11,13,15])
c=np.stack((a,b),axis=1)
print(c)

[[ 1 10]
 [ 2 11]
 [ 3 13]
 [ 4 15]]


In [89]:
a=np.array([1,2,3,4]) #using hstack to join(horizontal)
b=np.array([10,11,13,15])
c=np.array([9,8,6,7])
d=np.hstack((a,b,c))
print(d)

[ 1  2  3  4 10 11 13 15  9  8  6  7]


In [90]:
a=np.array([1,2,3,4]) #using vstack to join(vertical)
b=np.array([10,11,13,15])
c=np.array([9,8,6,7])
d=np.vstack((a,b,c))
print(d)

[[ 1  2  3  4]
 [10 11 13 15]
 [ 9  8  6  7]]


In [91]:
a=np.array([1,2,3,4]) #using dstack to join: deals with height and depth
b=np.array([10,11,13,15])
c=np.array([9,8,6,7])
d=np.dstack((a,b,c))
print(d)

[[[ 1 10  9]
  [ 2 11  8]
  [ 3 13  6]
  [ 4 15  7]]]


In [92]:
#spliting numpy array: it is a reverse operation of an array.Array_split# read( dsplit, vsplit and hsplit)
a=np.array([1,2,3,4,6,7,8])
b=np.array_split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([6, 7]), array([8])]


In [93]:
b[0]

array([1, 2])

In [94]:
b[1]

array([3, 4])

In [95]:
b[2]

array([6, 7])

In [96]:
b[3]

array([8])

In [97]:
a=np.array([[1,2], [3,4],[5,6],[7,8],[9,10],[11,12]])
b=np.array_split(a,3)
print(b)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [98]:
b[0]

array([[1, 2],
       [3, 4]])

In [99]:
b[1]

array([[5, 6],
       [7, 8]])

In [100]:
b[2]

array([[ 9, 10],
       [11, 12]])

In [101]:
b[:]

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [102]:
# Searching an array by showing the index position of your search
a=np.array([1,2,3,4,5,4])
x=np.where(a==4)
print(x)

(array([3, 5], dtype=int64),)


In [103]:
a=np.array([1,2,3,4,5,4])#printing out the index positn of the index even element
x=np.where(a%2==0)
print(x)

(array([1, 3, 5], dtype=int64),)


In [104]:
#search sorted  in numpy. it performs binary search in an array

In [105]:
a=np.array([1,2,4,3,5,6]) # it will signify where 4 should be.it normally count from left hand.
x=np.searchsorted(a,4)
print(x)

4


In [106]:
a=np.array([1,2,4,3,5,6]) # it will signify where 4 should be.it normally count from right hand.
x=np.searchsorted(a,7, side='right')
print(x)

6


In [107]:
#Sort
a=np.array([1,2,3,4,7,6])
print(np.sort(a))


[1 2 3 4 6 7]


In [108]:
b=np.array(['ife', 'Justice', 'ik'])
print(np.sort(b))

['Justice' 'ife' 'ik']


In [109]:
c=np.array([True,False,True])
print(np.sort(c))

[False  True  True]


In [110]:
a=np.array([[9,23,1],[11,7,2]])
print(np.sort(a))

[[ 1  9 23]
 [ 2  7 11]]


In [111]:
a=np.array([3,7,2,1,9,5,10])
print(np.sort(a))

[ 1  2  3  5  7  9 10]


In [113]:
a=np.arange(0,20)
b=np.where(a%2==0)
print(b)

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64),)


In [115]:
a=np.arange(21,40)
b=np.where(a%2==0)
print(b)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17], dtype=int64),)


In [116]:
a=np.arange(21,40,2)
a

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [118]:
a=np.arange(0,40)
b=np.where(a%2!=0)
print(b)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39], dtype=int64),)


In [119]:
a=np.arange(0,40)
b=np.where(a%5==0)
print(b)

(array([ 0,  5, 10, 15, 20, 25, 30, 35], dtype=int64),)


In [120]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [121]:
np.zeros(3)

array([0., 0., 0.])

In [122]:
np.zeros((2,3)) # 2=row and 3=column

array([[0., 0., 0.],
       [0., 0., 0.]])

In [123]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [128]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [130]:
a=np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [133]:
a=np.linspace(0,10,7)
a

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [134]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [135]:
a=np.random.rand(3)
a

array([0.75413021, 0.8317527 , 0.08588721])

In [136]:
a=np.random.rand(5)
a

array([0.53289057, 0.05131699, 0.27529297, 0.01350912, 0.36423931])

In [160]:
b=np.random.rand(5,3,3)
b

array([[[0.55940942, 0.77566145, 0.65831494],
        [0.60512898, 0.01242877, 0.08541648],
        [0.28621141, 0.3070009 , 0.64994076]],

       [[0.16461006, 0.36049595, 0.95816892],
        [0.32315071, 0.06151023, 0.14930356],
        [0.56608577, 0.31679386, 0.26418453]],

       [[0.21066611, 0.1980506 , 0.42835492],
        [0.5536143 , 0.46657796, 0.28301309],
        [0.87671373, 0.51035226, 0.64404001]],

       [[0.03494311, 0.03566209, 0.21310827],
        [0.57811666, 0.06603972, 0.04293333],
        [0.74517291, 0.82049682, 0.9353534 ]],

       [[0.33439574, 0.60112525, 0.24938939],
        [0.65855494, 0.27221872, 0.61776334],
        [0.59571671, 0.30456317, 0.26778365]]])

In [159]:
c=np.random.randn(5)
c

array([ 2.06325516, -0.2439874 , -0.61878734,  1.11814691,  1.47883049])

In [157]:
d=np.random.rand(3,5)
d

array([[0.90914523, 0.23464816, 0.1229855 , 0.46701189, 0.37811598],
       [0.54165265, 0.15806843, 0.2152441 , 0.20056355, 0.1830719 ],
       [0.18414922, 0.74752734, 0.44161113, 0.1286523 , 0.17722792]])

In [158]:
e=np.random.randint(0,50,20) #0=start, 50=stop, 20=size, randit doesnt have step like in other cases.it deals with intiger and not float
e

array([47,  0, 17, 14, 17, 31, 15, 25, 34, 11, 26, 15, 42,  1, 27, 13,  8,
       47, 12,  0])

In [148]:
e.reshape(4,5)


array([[24, 31, 34, 39, 19],
       [27, 22, 45, 30,  3],
       [42, 19, 32, 30, 33],
       [34,  1, 38, 12,  7]])

In [149]:
e.max()

45

In [150]:
e.min()

1

In [151]:
e.argmax()

7

In [152]:
e.argmin()

16